# ----------------------------------------------------------------------------------------------------
# Pipeline to build and deploy one Container App Module
# ----------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: 'ubuntu-latest'
# ----------------------------------------------------------------------------------------------------
trigger: none

# ----------------------------------------------------------------------------------------------------
parameters:
- name: apps
  displayName: Which App to build and deploy?
  type: string
  values:
    - ui
    - none
  default: 'ui'
- name: buildApps
  displayName: Build Docker Images
  type: boolean
  default: true
- name: pushApps
  displayName: Push Images to ACR
  type: boolean
  default: true
- name: deployApps
  displayName: Deploy from ACR to CA
  type: boolean
  default: true
- name: runMSDevSecOpsScan
  displayName: Run Scan
  type: boolean
  default: false

# ----------------------------------------------------------------------------------------------------
variables:
  - group: AI.LZ.Secrets
  - template: vars/var-service-connections.yml

# ----------------------------------------------------------------------------------------------------
stages:
- ${{ if parameters.runMSDevSecOpsScan }}:
    - stage: ScanApplication
      displayName: Scan Application
      jobs:
        - template: pipes/templates/scan-code-template.yml
          parameters:
            environmentName: 'DEV'
            runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
            runGHASScan: false

# ----------------------------------------------------------------------------------------------------
- ${{ if and(parameters.buildApps, contains(lower(parameters.apps), 'api')) }}:
  - template: pipes/aca-build-one-pipe.yml
    parameters:
      pushToACR: ${{ parameters.pushApps }}
      apps: [ 
        { containerAppName: 'api', acrAppName: 'chatapi', projectFolderName: 'src/api/chatapi',    port: '8080' }
      ] 

- ${{ if and(parameters.buildApps, contains(lower(parameters.apps), 'ui')) }}:
  - template: pipes/aca-build-one-pipe.yml
    parameters:
      pushToACR: ${{ parameters.pushApps }}
      apps: [ 
        { containerAppName: 'ui',  acrAppName: 'chatui',  projectFolderName: 'src/website/chatui', port: '8080' }
      ] 

# ----------------------------------------------------------------------------------------------------
- ${{ if and(parameters.deployApps, contains(lower(parameters.apps), 'api')) }}:
  - template: pipes/aca-deploy-pipe.yml
    parameters:
      apps: [ 
        { containerAppName: 'api', acrAppName: 'chatapi', projectFolderName: 'src/api/chatapi',    port: '8080' }
      ] 

- ${{ if and(parameters.deployApps, contains(lower(parameters.apps), 'ui')) }}:
  - template: pipes/aca-deploy-pipe.yml
    parameters:
      apps: [ 
        { containerAppName: 'ui',  acrAppName: 'chatui',  projectFolderName: 'src/website/chatui', port: '8080' }
      ] 
