# ----------------------------------------------------------------------------------------------------
# Template to build a Azure Container App Docker image and put it to a container registry
# ----------------------------------------------------------------------------------------------------
# This template gets the appName from the variable group: AI.LZ.Secrets
#   and the resource group name from /vars/var-<env>.yml
# ----------------------------------------------------------------------------------------------------
parameters:
  - name: serviceConnectionName
    type: string
  - name: environmentCode
    type: string
    default: 'DEV'
  - name: pushToACR
    default: true
    type: boolean
  - name: updateFirewall
    default: true
    type: boolean
  - name: acrFolderName
    default: 'appImages'
    type: string

  - name: apiAcrAppName
    default: ''
    type: string
  - name: apiProjectFolderName
    default: ''
    type: string

  - name: uiAcrAppName
    default: ''
    type: string
  - name: uiAcrAppName
    default: ''
    type: string

# ----------------------------------------------------------------------------------------------------
jobs:
  - deployment: BuildMultipleApps
    displayName: Init Build Apps ${{ parameters.environmentcode }}
    environment: ${{ parameters.environmentcode }}

  - job: BuildMultiple${{ parameters.environmentcode }}Job
    displayName: Build Multiple ${{ parameters.environmentcode }}
    variables:
      - group: AI.LZ.Secrets # need to get the appName from here
      # Bring in environment specific variable files
      - ${{ if eq(lower(parameters.environmentcode), 'dev') }}:
          - template: ../../vars/var-dev.yml
      - ${{ if eq(lower(parameters.environmentcode), 'qa') }}:
          - template: ../../vars/var-qa.yml
      - ${{ if eq(lower(parameters.environmentcode), 'prod') }}:
          - template: ../../vars/var-prod.yml

    steps:
      # ----------------------------------------------------------------------------------------------------
      # Set up the environment variables
      # ----------------------------------------------------------------------------------------------------
      - task: PowerShell@2
        name: createVariables
        displayName: Create Variables
        continueOnError: true
        inputs:
          targetType: 'inline'
          script: |
            $environmentCodeLower="${{ parameters.environmentcode }}".ToLower()
            echo "##vso[task.setvariable variable=environmentCodeLower]$environmentCodeLower"
            $appNameLower="$(APP_NAME)".ToLower()
            echo "##vso[task.setvariable variable=appNameLower]$appNameLower"
            $appNameNoDashesLower="$(APP_NAME)".ToLower().Replace("-", "")

            $resourceGroupName="$(RESOURCEGROUP_PREFIX)-$environmentCodeLower-$(INSTANCE_NUMBER)".ToLower()
            echo "##vso[task.setvariable variable=resourceGroupName]$resourceGroupName"
            
            echo "##vso[task.setvariable variable=appNameNoDashesLower]$appNameNoDashesLower"
            $acrFolderNameLower="${{ parameters.acrFolderName }}".ToLower()
            echo "##vso[task.setvariable variable=acrFolderNameLower]$acrFolderNameLower"
            $containerRegistryName="$($appNameNoDashesLower)cr$($environmentCodeLower)"
            echo "##vso[task.setvariable variable=containerRegistryName]$containerRegistryName"
            $containerRegistryUrl="$($appNameNoDashesLower)cr$($environmentCodeLower).azurecr.io"
            echo "##vso[task.setvariable variable=containerRegistryUrl]$containerRegistryUrl"
            $agentIpAddress = $(Invoke-WebRequest -Uri "https://api.ipify.org").Content
            echo "##vso[task.setvariable variable=agentIpAddress]$agentIpAddress"

            $apiAcrAppNameLower="${{ parameters.apiAcrAppName }}".ToLower()
            echo "##vso[task.setvariable variable=apiAcrAppNameLower]$apiAcrAppNameLower"
            $apiImageName="$($acrFolderNameLower)/$($apiAcrAppNameLower):$(Build.BuildId)"
            echo "##vso[task.setvariable variable=apiImageName]$apiImageName"
            $apiImageNameBranch="$($acrFolderNameLower)/$($apiAcrAppNameLower):$(Build.SourceBranchName)"
            echo "##vso[task.setvariable variable=apiImageNameBranch]$apiImageNameBranch"

            $uiAcrAppNameLower="${{ parameters.uiAcrAppName }}".ToLower()
            echo "##vso[task.setvariable variable=uiAcrAppNameLower]$uiAcrAppNameLower"
            $uiImageName="$($acrFolderNameLower)/$($uiAcrAppNameLower):$(Build.BuildId)"
            echo "##vso[task.setvariable variable=uiImageName]$uiImageName"
            $uiImageNameBranch="$($acrFolderNameLower)/$($uiAcrAppNameLower):$(Build.SourceBranchName)"
            echo "##vso[task.setvariable variable=uiImageNameBranch]$uiImageNameBranch"

            echo "appNameLower=$appNameLower"
            echo "appNameNoDashesLower=$appNameNoDashesLower"
            echo "resourceGroupName=$resourceGroupName"
            echo "containerRegistryName=$containerRegistryName"
            echo "containerRegistryUrl=$containerRegistryUrl"
            echo "acrFolderNameLower=$acrFolderNameLower"
            echo "agentIpAddress=$agentIpAddress"
            echo "serviceConnectionName=$(serviceConnectionName)"

            echo "parameters.apiAcrAppName=${{ parameters.apiAcrAppName }}"
            echo "apiAcrAppNameLower=$apiAcrAppNameLower"
            echo "apiImageName=$apiImageName"
            echo "apiImageNameBranch=$apiImageNameBranch"

            echo "parameters.uiAcrAppName=${{ parameters.uiAcrAppName }}"
            echo "uiAcrAppNameLower=$uiAcrAppNameLower"
            echo "uiImageName=$uiImageName"
            echo "uiImageNameBranch=$uiImageNameBranch"

            echo "----------------------------------------"
            echo "##[group]Display All Environment Variables:"
            printenv | sort
            echo "##[endgroup]"

            echo "----------------------------------------"
            echo "##[group]Directory of pipeline workspace:"
            tree -L 4 $(Pipeline.Workspace)
            echo "##[endgroup]"

      # ----------------------------------------------------------------------------------------------------
      # Build the images
      # ----------------------------------------------------------------------------------------------------
      - task: PowerShell@2
        displayName: Docker API Build
        inputs:
          targetType: 'inline'
          script: |
            echo "Executing: docker build . $(apiImageName)"
            docker build . -t $(apiImageName) -t $(apiImageNameBranch)
            docker images
          workingDirectory: '$(System.DefaultWorkingDirectory)/${{ parameters.apiProjectFolderName }}'

      - task: PowerShell@2
        displayName: Docker UI Build
        inputs:
          targetType: 'inline'
          script: |
            echo "Executing: docker build . $(uiImageName)"
            docker build . -t $(uiImageName) -t $(uiImageNameBranch)
            docker images
          workingDirectory: '$(System.DefaultWorkingDirectory)/${{ parameters.uiAcrAppName }}'

      # ----------------------------------------------------------------------------------------------------
      # ACR Push: Push to ACR, add/remove firewall rules and remove if requested
      # ----------------------------------------------------------------------------------------------------
      - ${{ if parameters.pushToACR }}:
        - template: steps-container-registry-template.yml
          parameters:
            action: 'add-login'
            serviceConnectionName: ${{ parameters.serviceConnectionName }}
            registryName: $(containerRegistryName)
            registryResourceGroup: $(resourceGroupName)
            updateFirewall: ${{ parameters.updateFirewall }}
            agentIpAddress: $(agentIpAddress)

        - template: steps-container-registry-template.yml
          parameters:
            action: 'push'
            imageName: $(apiImageName)
            imageNameLatest: $(apiImageNameBranch)
            serviceConnectionName: ${{ parameters.serviceConnectionName }}
            registryName: $(containerRegistryName)
            registryResourceGroup: $(resourceGroupName)
            updateFirewall: ${{ parameters.updateFirewall }}
            agentIpAddress: $(agentIpAddress)

        - template: steps-container-registry-template.yml
          parameters:
            action: 'push'
            imageName: $(uiImageName)
            imageNameLatest: $(uiImageNameBranch)
            serviceConnectionName: ${{ parameters.serviceConnectionName }}
            registryName: $(containerRegistryName)
            registryResourceGroup: $(resourceGroupName)
            updateFirewall: ${{ parameters.updateFirewall }}
            agentIpAddress: $(agentIpAddress)

        - template: steps-container-registry-template.yml
          parameters:
            action: 'remove'
            serviceConnectionName: ${{ parameters.serviceConnectionName }}
            registryName: $(containerRegistryName)
            registryResourceGroup: $(resourceGroupName)
            updateFirewall: ${{ parameters.updateFirewall }}
            agentIpAddress: $(agentIpAddress)
